# NeON build file (http://github.com/c4s4/neon)

extends: c4s4/build/go-tool.yml
default: run

properties:
  LIBRARIES:
  - 'github.com/mitchellh/gox'
  - 'github.com/mattn/go-zglob'
  - 'github.com/udhos/equalfile'

targets:

  run:
    doc: Run backup
    depends: bin
    steps:
    - time:
      - $: 'build/backup'
